[tox]
envlist = py39
skipsdist = True

[testenv]
allowlist_externals =
    pytest
    python
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest
    pytest-cov
    PyYAML
commands =
    python -m pip install -e .
    pytest --cov=gendiff --cov-report=xml --cov-branch tests/